import {Injectable} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {ImageOverlay, LatLng, latLng, Layer, TileLayer, tileLayer} from 'leaflet';
import {Observable} from 'rxjs';
import {Backend} from './backend.model';

@Injectable({
    providedIn: 'root'
})
export class MapService {

    public map;
    public stateIsSelected: boolean;
    public states: Backend[];
    public possibleRaces: Backend[];
    public elections: Backend[];
    public nameToLayerMapper = new Map<string, ImageOverlay>();
    public selectedState: string;

    private mapUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
    private REST_API_SERVER_URL = 'http://localhost:8080';
    private options: { center: LatLng; layers: TileLayer[]; zoom: number };
    private layerIdToNameMapper = new Map<string, string>();

    constructor(private http: HttpClient) {
        this.stateIsSelected = false;
        this.states = [
            {name: 'West Virginia', backendName: 'WEST_VIRGINIA'},
            {name: 'Utah', backendName: 'UTAH'},
            {name: 'Florida', backendName: 'FLORIDA'}
        ];
        this.possibleRaces = [
            {name: 'White', backendName: 'WHITE'},
            {name: 'African American', backendName: 'BLACK'},
            {name: 'Latino', backendName: 'LATINO'},
            {name: 'Asian', backendName: 'ASIAN'},
            {name: 'Pacific Islander', backendName: 'PACIFIC_ISLANDER'},
            {name: 'Native American', backendName: 'NATIVE_AMERICAN'},
        ];
        this.elections = [
            {name: 'Presidential 2016', backendName: 'PRESIDENTIAL_2016'},
            {name: 'Congressional 2016', backendName: 'CONGRESSIONAL_2016'},
            {name: 'Congressional 2018', backendName: 'CONGRESSIONAL_2018'},
        ];

    }

    getOptions() {
        this.options = {
            layers: [
                tileLayer(this.mapUrl, {maxZoom: 18, attribution: '...'}),
            ],
            zoom: 4,
            center: latLng(37.6, -95.665)
        };
        return this.options;
    }

    setSelectedState(selectedState: string): void {
        this.selectedState = selectedState;
        this.stateIsSelected = true;
        console.log(selectedState);
        this.map.fitBounds(this.nameToLayerMapper.get(selectedState).getBounds());
        // TODO make sure the uncomment this when you start interacting with the server again
        // this.http.post<Config>(this.REST_API_SERVER_URL + '/setState', selectedState).subscribe();
    }

    setMap(map) {
        this.map = map;
    }

    /**
     * Gets the id of the given layer
     * @param layer:Layer The layer that you want to get the id of
     * @return Number     The number that is the leaflet_id
     */
    getLayerId(layer: Layer) {
        return (layer as any)._leaflet_id;
    }

    /**
     * Gets the Layer Id of the GeoJson created layer
     * @param  geoJson: any   The GeoJson Object generated by Leaflet
     *
     * @return Number        The number that is the leaflet_id
     */
    getGeoJsonId(geoJson) {
        const temp = Object.getOwnPropertyNames((geoJson as any)._layers);
        const temp2 = Object.getOwnPropertyNames((geoJson as any)._layers[temp[0]]._layers);
        return (geoJson as any)._layers[temp[0]]._layers[temp2[0]]._leaflet_id;
    }

    /**
     * Gets the layer buried in the GeoJson
     * @param  geoJson: any    The GeoJson Object generated by Leaflet
     * @return Layer          The buried layer
     */
    getGeoJsonLayer(geoJson) {
        const temp = Object.getOwnPropertyNames((geoJson as any)._layers);
        const temp2 = Object.getOwnPropertyNames((geoJson as any)._layers[temp[0]]._layers);
        return (geoJson as any)._layers[temp[0]]._layers[temp2[0]];
    }

    addLayerIdAndName(layerId, name) {
        this.layerIdToNameMapper.set(layerId, name);
    }

    addNameAndLayer(name, layer) {
        this.nameToLayerMapper.set(name, layer);
    }

    getNameOfLayer(layer) {
        return this.layerIdToNameMapper.get(layer);
    }

    getFlorida(): Observable<any> {
        return this.http.get('assets/florida.json');
    }

    getUtah(): Observable<any> {
        return this.http.get('assets/utah.json');
    }

    getWestVirginiaGeoJson(): Observable<any> {
        // return this.http.get('assets/westVirginia.json');
        return this.http.get(this.REST_API_SERVER_URL + '/westVirginia');
    }
}
